---
- name: Настройка сервера для Site Checker
  hosts: sitechecker
  become: yes
  
  vars:
    domain_name: "sitechecker-diplom.mooo.com"
    certbot_email: "radima.m@list.ru"  
  
  roles:
    - docker
    - nginx
    - certbot
    - app
